export const accessories = [
  { hide: false, label: 'Alarme', value: 'alarme' },
  { hide: false, label: 'Ar-Condicionado', value: 'ar-condicionado' },
  { hide: false, label: 'Vidros elétricos', value: 'vidros elétricos' },
  { hide: false, label: 'Travas elétricas', value: 'travas elétricas' },
  { hide: false, label: 'Multimídia', value: 'multimídia' },
  { hide: false, label: 'Bancos em couro', value: 'bancos em couro' },
  { hide: false, label: 'Controles no volante', value: 'controles no volante' },
  { hide: false, label: 'Rebatimento aut dos retrovisores', value: 'rebatimento aut dos retrovisores' },
  { hide: false, label: 'Retrovisor fotocromico', value: 'retrovisor fotocromico' },
  { hide: false, label: 'Limpador traseiro', value: 'limpador traseiro' },
  { hide: false, label: 'DLR', value: 'dlr' },
  { hide: false, label: 'Faróis LED', value: 'faróis led' },
  { hide: false, label: 'Rodas de liga leve', value: 'rodas de liga leve' },
];